name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test1
      id: test1
      uses: education/autograding-command-grader@v1
      with:
        test-name: Test1
        setup-command: npm install
        command: npm test 1
        timeout: 10
    - name: Test 2
      id: test-2
      uses: education/autograding-command-grader@v1
      with:
        test-name: Test 2
        setup-command: npm install
        command: npm test 2
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST1_RESULTS: "${{steps.test1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
      with:
        runners: test1,test-2
